/* Clear */
DELETE FROM ITENS;

DELETE FROM PRODUTOS;

DELETE FROM PEDIDOS;

DELETE FROM CLIENTES;

/* Insert */

INSERT INTO CLIENTES VALUES (1, 'Papelaria Teste da esquina', CURRENT_TIMESTAMP());
INSERT INTO CLIENTES VALUES (2, 'Escritorio Teste Associados', CURRENT_TIMESTAMP());

INSERT INTO PRODUTOS VALUES(1, 'LÁPIS',1.1,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(2, 'CADERNO',1,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(3, 'BORRACHA',0.5,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(4, 'PAPEL SULFITE (500 FL)',4,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(5, 'CANETA',1.7,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(6, 'PINCEL',2.1,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(7, 'REGUA',2.4,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(8, 'CLIPS CX COM 100 UN',3,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(9, 'FITA ADESIVA',3,CURRENT_TIMESTAMP());
INSERT INTO PRODUTOS VALUES(10, 'GRAMPEADOR',6,CURRENT_TIMESTAMP());

INSERT INTO PEDIDOS VALUES (1, 1, CURRENT_TIMESTAMP());

INSERT INTO ITENS VALUES (1, 1, 1.1,75, CURRENT_TIMESTAMP());
INSERT INTO ITENS VALUES (1, 4, 4, 15, CURRENT_TIMESTAMP());
INSERT INTO ITENS VALUES (1, 3, 0.5,50, CURRENT_TIMESTAMP());
INSERT INTO ITENS VALUES (1, 7, 2.4,25, CURRENT_TIMESTAMP());
INSERT INTO ITENS VALUES (1, 10, 6,10, CURRENT_TIMESTAMP());

